import React, { useState } from "react";
import rioSmall from "../assets/icons/unsw_logo.png";
import rioBig from "../assets/icons/unsw_logo_text.png";
import SuggestionSummary from "../src/components/SuggestionSummary";
import DimensionFilterPanel from "../src/components/DimensionFilterPanel";
import TopRouteTabs from "../src/components/TopRouteTabs";

export default function CultureAnalysis() {

  const [dimension, setDimension]     = useState("");
  const [subtheme, setSubtheme]       = useState(""); 
  const [subthemeFile, setSubthemeFile] = useState("");

  return (
    <div
      className="min-h-screen font-display"
      style={{ background: "rgb(242,241,237)" }}
    >
      <div
        className="
          px-7 pt-7 grid gap-x-6 gap-y-6
          grid-cols-1
          sm:grid-cols-[0px_minmax(0,1fr)]
          lg:grid-cols-[0px_minmax(0,1fr)_minmax(300px,420px)]
          xl:grid-cols-[0px_minmax(0,1fr)_420px]
        "
      >

        <div className="hidden sm:flex row-start-1 col-start-1 flex-col items-center self-start">
          <img src={rioSmall} alt="RIO" className="h-10 w-auto mt-[5px]" />
          <img
            src={rioBig}
            alt="Rio Tinto"
            className="h-3 w-auto mt-[3.5px] grayscale"
          />
        </div>


        <div className="row-start-1 col-start-1 sm:col-start-2 flex items-center self-start">
          <div className="translate-y-[2px]">
            <h1 className="text-xl md:text-4xl font-semibold text-neutral-900">
              Culture Analysis
            </h1>
            <p className="text-sm md:text-base text-neutral-500 hidden xl:block">
              High-level culture insights generated by the system.
            </p>
          </div>
        </div>


        <div className="row-start-2 sm:row-start-1 col-start-1 sm:col-start-2 lg:col-start-3 w-full self-start mt-1.5">
          <TopRouteTabs />
        </div>


        <section className="row-start-3 sm:col-start-2 lg:row-span-2">
          <SuggestionSummary
            className="h-[720px]"
            dimension={dimension}
            subthemeFile={subthemeFile}
            onBack={(level) => {

              if (level === "dimension") {
                setSubtheme("");
                setSubthemeFile("");
              } else if (level === "overall") {
                setDimension("");
                setSubtheme("");
                setSubthemeFile("");
              }
            }}
          />
        </section>


        <aside className="row-start-3 sm:col-start-2 lg:col-start-3 lg:row-span-2">
          <DimensionFilterPanel
            className="h-[720px]"
            onSelect={(dim, sub, file) => {
              setDimension(dim || "");
              setSubtheme(sub || "");
              setSubthemeFile(file || "");
            }}
          />
        </aside>
      </div>
    </div>
  );
}
